### ISSUE TITLE
Create a List of goals and write simple dev Readme

### ISSUE THREAD

**Issue by shadows-eye** [SR5-FoundryVTT/Foundry-SR5-Biomonitor#1]
Add a List of Goals / Functions of the Modul and Write a dev Readme on how to start development on this Modul.

**Comment by Stexinator** [comment]
How to use the module?

    How to get Actors into the view?
    How to configure which statuses are displayed?
    Which interaction can be done?
    Do we want a details view?

What is our MVP?

    I think showing all player controlled character/critter actors should be fine
    I think showing all statuses is fine
    Minimal functionality should be tracks, statuses and image

After the MVP we can revisit our broader goals to determine the next step

**Comment by shadows-eye** [comment]
On your first Question I would say: 

1. with a + button giving the GM a list of all actors in the world to choose from
2. Additionly while the monitor is open per drag and drop onto the Monitor
3. As GM select multiply actors on the canvas and hit a button on the Monitor "Observe Actors"
4. As Player select multiply actors on the canvas (only owned ones) and hit a button on the Monitor "Observe Actors"

**Comment by shadows-eye** [comment]
On the secound question, what statuses would you want to show? (Drugs, Poisend?)

**Comment by Stexinator** [comment]
I gave it some thought and would add some settings if

- only player controlled actors can be monitored
- which type of actor can be monitored
- if the actor needs a certain item to be monitored

With this the gm can also allow their rigger to have their drones in the monitor

**Comment by Stexinator** [comment]
I close this issue and make new ones
